version: '3.8'

services:
    rt1:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        sysctls:
          - net.ipv4.icmp_echo_ignore_broadcasts=0
    rt2:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        sysctls:
          - net.ipv4.icmp_echo_ignore_broadcasts=0
    rt3:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        sysctls:
          - net.ipv4.icmp_echo_ignore_broadcasts=0
networks:
    dmz: {}
